config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :users, only: [:show,:index,:edit,:update]
  resources :books, only: [:create, :index, :show, :edit, :destroy,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user

    validates :title, presence: true
    validates :body, {presence: true, length: {maximum: 200} }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :books, dependent: :destroy
        attachment :profile_image

        validates :name,  {uniqueness: true,length: { in: 2..20 } }
        validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Sign in successfully"
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    flash[:notice] = "sign up successfully"
    user_path(current_user.id)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    flash[:notice] = "Create successfully"
    redirect_to book_path(@book.id)
   else
    @books = Book.all
    @user = current_user
    render(:index)
   end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
      flash[:notice] = "Update successfully"
      redirect_to book_path(@book.id)
   else
     render:edit
   end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
           flash[:notice] = "Create successfully"
           redirect_to book_path(@book.id)
        else


        end
    end


    def show
        @book = Book.new
        @user = User.find(params[:id])
        @books = @user.books.reverse_order
    end

    def index
        @book = Book.new
        @users = User.all
    end

    def edit
        @user = User.find(params[:id])
        redirect_to user_path(current_user.id) unless current_user.id == @user.id
    end

    def update
        @user = User.find(params[:id])
       if  @user.update(user_params)
           flash[:notice] = "Update successfully"
           redirect_to user_path(@user.id)
       else
          render :edit
       end
    end

    private

    def user_params
        params.require(:user).permit(:name,:introduction,:profile_image_id,)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
        <% @book.errors.full_messages.each do |message| %>
        <%= "error" %>
        <%= message %>
        <% end %>
        <% end %>
       <%= form_with model:@book, local:true do |f| %>
        <label for="inputTitle">Title</label>
        <p><%= f.text_field :title, autofocus: true, id:"inputTitle"%></p>
        <label for="inputBody">Opinion</label>
        <p><%= f.text_area :body, id:"inputBody" %></p>
        <%= f.submit "Update Book" %>
       <% end %>
       <%= link_to "Show",book_path(@book.id) %> | <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <% if @book.errors.any? %>
            <% @book.errors.full_messages.each do |message| %>
            <%= "error" %>
            <%= message %>
            <% end %>
            <% end %>
            <h2>User info</h2>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
             <table class="table">
                 <tbody>
                     <tr>
                         <th>name</th>
                         <th><%= current_user.name %></th>
                     </tr>
                     <tr>
                         <th>introduction</th>
                         <th><%= current_user.introduction %></th>
                     </tr>
                 </tbody>
             </table>
             <div claa="row ">
                 <%= link_to edit_user_path(current_user.id), class:'btn btn-outline-secondary btn-block' do %>
                 <i class="fas fa-user-cog"></i>
                 <% end %>
             </div>

            <h2 class="mt-3">New book</h2>
            <%= form_with model: @book, local:true do |f| %>
            <label for="book_title">Title</label>
            <p><%= f.text_field :title %></p>
            <label for="book_opinion">Opinion</label>
            <p><%= f.text_area :body %></p>
            <%= f.submit 'Create Book' %>
            <% end %>
        </div>
        <div class= "col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @books.each do |book| %>
                    <tr>
                        <td>
                            <%= link_to user_path(book.user.id) do %>
                            <%= attachment_image_tag @user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg" %>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to book_path(book.id) do %>
                            <%= book.title %>
                            <% end %>
                        </td>
                        <td>
                            <%= book.body %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
             <table class="table">
                 <tbody>
                     <tr>
                         <th>name</th>
                         <th><%= @user.name %></th>
                     </tr>
                     <tr>
                         <th>introduction</th>
                         <th><%= @user.introduction %></th>
                     </tr>
                 </tbody>
             </table>
             <div claa="row ">
                 <% if @user.id == current_user.id %>
                     <%= link_to edit_user_path(current_user.id), class:'btn btn-outline-secondary btn-block fas fa-user-cog' do %>
                     <i class="fas fa-user-cog"></i>
                     <% end %>
                 <% else %>
                     <%= link_to edit_user_path(@user.id), class:'btn btn-outline-secondary btn-block' do %>
                     <i class="fas fa-user-cog"></i>
                     <% end %>
                 <% end %>
             </div>

            <h2 class="mt-3">New book</h2>
            <%= form_with model: @books, local:true do |f| %>
            <label for="book_title">Title</label>
            <p><%= f.text_field :title %></p>
            <label for="book_opinion">Opinion</label>
            <p><%= f.text_area :body %></p>
            <%= f.submit 'Create Book' %>
            <% end %>
        </div>
        <div class= "col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <td>
                          <%= link_to user_path(@user.id) do %>
                            <%= attachment_image_tag @user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg" %><br><%= @user.name %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to book_path(@book.id) do %>
                          <%= @book.title %>
                          <% end %>
                        </td>
                        <td><%= @book.body %></td>
                        <% if @user.id == current_user.id %>
                        <td>
                          <%= link_to edit_book_path(@book.id) do %>
                          <li class="btn btn-sm btn-success">Edit</li>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to book_path(@book.id), method: :delete do %>
                          <li class="btn btn-sm btn-danger" data-confirm="本当に消しますか？" >Destroy</li>
                          <% end %>
                        </td>
                         <% end %>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to <i class="fas fa-book"></i> <strong>Bookers</strong>!!
      </h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <%= link_to 'Log in', new_user_session_path , class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>

      <%= link_to 'Sign Up', new_user_registration_path , class: 'btn btn-success btn-sm btn-block sign_up' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <%= link_to root_path, class: 'text-white' do %>
            Bookers
          <% end %>
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> logout
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path , class: 'nav-link text-light' do %>
                <i class= "fas fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path , class: 'nav-link text-light' do %>
                <i class= "fas fa-user-plus"></i> sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path , class: 'nav-link text-light' do %>
                <i class= "fas fa-sign-in-alt"></i> login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if flash %>
  <%= flash[:notice] %>
<% end %>
    <%= yield %>
    <footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<div  class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |message| %>
        <%= "error" %>
        <%= message %>
        <% end %>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
          <label for="inputName">Name</label>
          <p><%= f.text_field :name, autofocus: true, id:"inputName"%></p>
          <label for="inputImage">Image</label>
          <p><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></p>
          <label for="inputIntroduction">Introduction</label>
          <p><%= f.text_area :introduction, id:"inputIntroduction" %></p>
          <%= f.submit "Update User" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
             <table class="table">
                 <tbody>
                     <tr>
                         <th>name</th>
                         <th><%= current_user.name %></th>
                     </tr>
                     <tr>
                         <th>introduction</th>
                         <th><%= current_user.introduction %></th>
                     </tr>
                 </tbody>
             </table>
             <div claa="row ">
                 <%= link_to edit_user_path(current_user.id), class:'btn btn-outline-secondary btn-block' do %>
                 <i class="fas fa-user-cog"></i>
                 <% end %>
             </div>

            <h2 class="mt-3">New book</h2>
            <%= form_with model: @book, local:true do |f| %>
            <label for="book_title">Title</label>
            <p><%= f.text_field :title %></p>
            <label for="book_opinion">Opinion</label>
            <p><%= f.text_area :body %></p>
            <%= f.submit 'Create Book' %>
            <% end %>
        </div>
        <div class= "col-md-8 offset-md-1">
            <h2>Users</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <td>
                            <%= attachment_image_tag user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg" %>
                        </td>
                        <td>
                            <%= user.name %>
                        </td>
                        <td>
                            <%= link_to "Show", user_path(user.id) %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
             <table class="table">
                 <tbody>
                     <tr>
                         <th>name</th>
                         <th><%= @user.name %></th>
                     </tr>
                     <tr>
                         <th>introduction</th>
                         <th><%= @user.introduction %></th>
                     </tr>
                 </tbody>
             </table>
             <div claa="row ">
                 <% if @user.id == current_user.id %>
                     <%= link_to edit_user_path(current_user.id), class:'btn btn-outline-secondary btn-block' do %>
                     <i class="fas fa-user-cog"></i>
                     <% end %>
                 <% else %>
                     <%= link_to edit_user_path(@user.id), class:'btn btn-outline-secondary btn-block' do %>
                     <i class="fas fa-user-cog"></i>
                     <% end %>
                 <% end %>
             </div>

            <h2 class="mt-3">New book</h2>
            <%= form_with model: @book, local:true do |f| %>
            <label for="book_title">Title</label>
            <p><%= f.text_field :title %></p>
            <label for="book_opinion">Opinion</label>
            <p><%= f.text_area :body %></p>
            <%= f.submit 'Create Book' %>
            <% end %>
        </div>
        <div class= "col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @books.each do |book| %>
                    <tr>
                        <td>
                          <%= link_to user_path(book.user.id) do %>
                            <%= attachment_image_tag @user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg" %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to book_path(book.id) do %>
                            <%= book.title %>
                            <% end %>
                        </td>
                        <td>
                            <%= book.body %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>